services:
  api:
    environment:
      APP_ENV: development
      APP_DEBUG: "true"
      BOT_MODE: polling
  bot:
    environment:
      APP_ENV: development
      APP_DEBUG: "true"
      BOT_MODE: polling
